Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -67,12 +67,21 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
 
-      - name: Login to GitHub Container Registry
-        uses: docker/login-action@v2
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      # Ajout d'une logique de ré-essai pour la connexion à la Container Registry
+      - name: Login to GitHub Container Registry with retry
+        run: |
+          for i in 1 2 3; do
+            if docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}; then
+              echo "Login successful"
+              exit 0
+            fi
+            echo "Login failed. Retrying in 10 seconds..."
+            sleep 10
+          done
+          echo "Failed to log in to ghcr.io after multiple retries."
+          exit 1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Extract metadata
         id: meta
@@ -160,7 +169,7 @@ jobs:
   destroy:
     name: Destroy Infrastructure
     needs: deploy
-    # The destroy job will only run if the 'destroy' input is set to true when the workflow is manually triggered.
+    # Le job de destruction ne s'exécutera que si l'entrée 'destroy' est définie sur 'true' lors du déclenchement manuel du workflow.
     if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.destroy == 'true' }}
     runs-on: ubuntu-latest
     steps:
